name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Select Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install Minification
        run: |
          npm install -g html-minifier-terser terser

      - name: Minify Assets
        run: |
          terser scripts.js --compress --mangle -o scripts.js
          npx lightningcss-cli --minify --targets "> 0.5%" styles.css -o styles.css
          html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css true index.html -o index.html

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5